<?xml version="1.0" encoding="utf-8"?>
<fileProperties>
    <ImageOverlay ScreenRectangle="1407,456,49,15" Profile="C:\Users\dale\Documents\My Profiles\MyProfile.capro" ProfileHash="f7cce08e97117b7176d16e7011cd84b7baed6a26" Rectangle="1407,456,49,15">
        <OriginalImage Type="Image" ShapeTimeSpan="10000" ExportFormat="png" Border="solid" BorderWidth="1" BorderColor="#696969" DPI="72" AutoAdjust="true" Format="tiff">SUkqABgBAACAP+BP8AQWDQeEQmFQuGQ2HQ+IRGJROKRWLQWBwSLxuOR2PR+QSGDRmRSWTSeUSmGSSVS2XS+YQ6WTGaTWbSKZx9rocZABCCxnABSk2b0WGLYAFsAksAKaPloALV/qUAEqLTmOUilUxTDBCABrM89gAU0azQhZlsAAEnU6LlpZQShxysRadz0VHpnwi4XKiWfANcAIUYioAHxoRKvWCxWSO3WJ1ql02F4uw2Oy4Cz2m122IX2hX+PZCIXcAXm9w/QXPNWbBYTDYiFZbG5mP6SG5KuRPaZjW2bOWy3QbV6KQ7iFabURvi7+ja/C4efYzfSbkQfdZSPVCpVSrc6b5y1VTWSjr+D0emrwP1e33RuAgBAA/gAEAAEAAAAAAAAAAAEEAAEAAAAxAAAAAQEEAAEAAAAPAAAAAgEDAAQAAADeAQAAAwEDAAEAAAAFAAAABgEDAAEAAAACAAAAEQEEAAEAAAAIAAAAFQEDAAEAAAAEAAAAFgEEAAEAAAAPAAAAFwEEAAEAAAAQAQAAGgEFAAEAAADmAQAAGwEFAAEAAADuAQAAHAEDAAEAAAABAAAAKAEDAAEAAAACAAAAPQEDAAEAAAACAAAAUgEDAAEAAAACAAAAAAAAAAgACAAIAAgAAHcBAOgDAAAAdwEA6AMAAA==</OriginalImage>
        <Shapes />
    </ImageOverlay>
</fileProperties>